### ISSUE TITLE
Why not remove the beta label

### ISSUE THREAD

**Issue by Starcounter-Jack** [MartinF/Dynamo.IoC#3]
I believe the beta label is a turn off. Any open issues warranting the beta status?

**Comment by MartinF** [comment]
I have changed a lot in the current version available here on GitHub compared to when it was first released, based on some of the feedback.
There is still a few things I haven't decided on. I don't know of any issues with the current version.

But I agree with you on the beta label, just need to brush it up and release it instead of keep changing stuff. :)
To start with I really just wanted an excuse to play around with Expressions and see what was possible.

**Comment by MartinF** [comment]
Also remindes me that I have to update the documentation/examples to reflect the new api.

**Comment by MartinF** [comment]
Removed in new version. I am about to update the documentation/examples.
