### ISSUE TITLE
.NET v4.0 compatibility

### ISSUE THREAD

**Issue by devatwork** [MartinF/Dynamo.IoC#7]
Hello Martin,

In version 3 of Dynamo you switched from .NET v4.0 to v4.5 as your target framework. My current codebase is running on v4.0.

When I upgraded to 3.0.0.1 I got the following error:
`Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.`

This error is caused by the fact that the ExtensionAttribute is moved from the System.Core to mscorlib assembly. See [http://stackoverflow.com/a/11265032](http://stackoverflow.com/a/11265032).

I have forked this project and changed the target framework back to v4.0, compiled it and include that assembly in my project, which fixed the problem for me.

So I was wondering if you plan to use v4.5 specific APIs? If not, we could add new projects targeting the v4.0 specifically. Via NuGet we can distribute runtime specific versions, see [http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package#Framework_Names](http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package#Framework_Names).

Regards,
Bert

**Comment by MartinF** [comment]
Hello Bert,

For now there is actually no reason for using v4.5.

Your suggestion seems like a very good idea, ill just need to try to find the time to make it happen :)

Best regards

Martin

-----Oprindelig meddelelse-----
Fra: Bert Willems [mailto:reply@reply.github.com] 
Sendt: 26. juli 2012 09:21
Til: Martin From
Emne: [DynamoIOC] .NET v4.0 compatibility (#7)

Hello Martin,

In version 3 of Dynamo you switched from .NET v4.0 to v4.5 as your target framework. My current codebase is running on v4.0.

When I upgraded to 3.0.0.1 I got the following error:
`Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.`

This error is caused by the fact that the ExtensionAttribute is moved from the System.Core to mscorlib assembly. See [http://stackoverflow.com/a/11265032](http://stackoverflow.com/a/11265032).

I have forked this project and changed the target framework back to v4.0, compiled it and include that assembly in my project, which fixed the problem for me.

So I was wondering if you plan to use v4.5 specific APIs? If not, we could add new projects targeting the v4.0 specifically. Via NuGet we can distribute runtime specific versions, see [http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package#Framework_Names](http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package#Framework_Names).

Regards,
Bert

---

Reply to this email directly or view it on GitHub:
https://github.com/MartinF/DynamoIOC/issues/7

**Comment by devatwork** [comment]
hallo Martin,

i can send you a pull-request today or tomorrow.

regards,
bert

**Comment by devatwork** [comment]
Pull request has been send, this issue is duplicate now.
